name: 02 - Workflow Events

on: 
    push:
        branches: 'feature/**'
    pull_request:
        types: [opened, reopened]
        branches: 'feature/**'
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Exibir o evento
              run: echo "Workflow disparado por ${{ github.event_name }}"

